### ISSUE TITLE
test

### ISSUE THREAD

**Issue by simonmau** [hope15/sepm_group#1]

**Comment by simonmau** [comment]
#

**Comment by simonmau** [comment]
Fix issue TG-2

**Comment by hope15** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Iso](https://trello.com/c/aX5ven1h/1-bug-iso)

**Comment by hope15** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pflichtenheft erhalten und aufbereiten](https://trello.com/c/ii1qE6Wj/2-pflichtenheft-erhalten-und-aufbereiten)
